# DO NOT MODIFY -- auto-generated by Apache Cordova

platform :ios, '9.0'

target 'c:\OSPanel\domains\moodlemobiledirectory\platforms\ios\LMS IBDA' do
	project 'c:\OSPanel\domains\moodlemobiledirectory\platforms\ios\LMS IBDA.xcodeproj'

end
